[settings]
db = "./stagelock.db" # path to sqlite3 db file
admin-auth-key = "admin-key" # key for admin routest (create/delete stage)
static-path = "./interface/dist" # path to interface dist (for production only)
port = 1323 # app port
debug = true # debug mode